### ISSUE TITLE
Cell value for Tmrt

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/local-effects#7]
Considering that in a cell there'll be different layer combinations, the final Tmrt for each cell should either be the weighted value of each of the layers or should we weight the flux (R) and get the final Tmrt from this. Which is the recommended approach?

**Comment by humerh** [comment]
From my point of view we should use the second approach:

The flux is defined in W/m2. Each layer contributes with each area to the total flux in the grid cell.
We should sum up the flux (in the cell,  over all layers and then apply the Bolzmann rule.

1)  R_ges = sum ( Ri * Fi ) over all layers      
           Ri .. flux for a specific layer
           Fi .. fraction of area of a specific layer
2)  T_mrt  = Bolzmann rule using 'R_ges'

**Comment by ghost** [comment]
I'm agree with Heinrich, it should be used the second approach.

**Comment by luis-meteogrid** [comment]
Hi, @ghilbrae @humerh @alecapolupo 

Ri does not stand for the flux of a specific layer but for the flux from a specific direction (upwards, downwards, east, west, north and south)

It may seem like a good approximation but the problem is that if we think about how one can contrast the calculations made with reality, one can either measure the radiant temperatures at a lower scale or measure the radiant temperature from a certain distance (height). Depending on the approach we take, one or the other approach may be better. In the first case what we would get is an average of the temperatures while in the second we would be observing the average energy flow I guess.

Our biggest problem is that we do not know how the theoretical values obtained are verified and what instrumentation is used for it.

In any case, we take note of your opinion and we will evaluate if it is easy to change the script since we were obtaining the global temperature as an average of the temperatures

**Comment by p-a-s-c-a-l** [comment]
> Our biggest problem is that we do not know how the theoretical values obtained are verified and what instrumentation is used for it.

Is that related to [this question](https://github.com/clarity-h2020/local-effects/issues/8#issuecomment-504909853)?

**Comment by luis-meteogrid** [comment]
We have been thinking about the way to verify the computed values for Tmrt and if you agree the following maybe a solution:
We check in some papers there exist open source tools that claim to behave well when calculating Tmrt, so we think we can use one of them Solweig 1.0 to do it. Maybe SMHI @LenaStr  or PLINIUS @alecapolupo know the Urban Climate Group at Goteborg University in which Fredrik Linberg works.
